version: '3'
services:
  web:
    image: samchatfield/coffeebot:latest
    command: npm start
    volumes:
      - ./.env:/usr/src/app/.env
      - /usr/src/app/node_modules/
    ports:
      - 80:8080
    restart: always